baseURL = ""
languageCode = "en-us"
title = "mitmproxy.org docs"
publishDir = "../public"
RelativeURLs = true
pygmentsCodefences = true
pygmentsUseClasses = true
sectionPagesMenu = 'main'

[indexes]
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[security.funcs]
getenv = ["DOCS_ARCHIVE"]
