name: autofix.ci

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: install-pinned/ruff@f8793aa7caf0b3196d6ed1370aea45f3c06304a3
      - run: ruff --fix-only .
      - run: ruff format .

      - name: Run prettier
        run: |
          npm ci
          npm run prettier
        working-directory: web

      - uses: mhils/add-pr-ref-in-changelog@main

      - uses: autofix-ci/action@d3e591514b99d0fca6779455ff8338516663f7cc
