name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - if: github.event_name == 'pull_request'
      uses: TrueBrain/actions-flake8@v1.2
    - if: github.event_name != 'pull_request'
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        flake8
  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v1
    - uses: actions/checkout@v1
    - name: Run mypy
      run: |
        python -m pip install --upgrade pip
        pip install mypy
        mypy .
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-python@v1
      with:
        architecture: 'x86'  # fixme
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: mitmdump --version
    - name: Test with pytest
      run: |
        pytest --timeout 60 --cov-report=xml \
          --cov=mitmproxy --cov=pathod \
          --full-cov=mitmproxy/ --full-cov=pathod/
    - uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
